version: '3.8'

services:
  php-apache:
    image: php:8.2-apache
    container_name: php-apache
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - "8088:80"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: parfpuna
      MYSQL_PASSWORD: parfpuna
      MYSQL_ROOT_HOST: "%"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8089:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
